package ua.com.travel.validationTent;

public interface ValidatorMessegeTent {
	
	String EMPTY_BRAND_FIELD = "EMPTY_BRAND_FIELD";
	String EMPTY_COPACITY_FIELD = "EMPTY_COPACITY_FIELD";
	String EMPTY_WEIGHT_FIELD = "EMPTY_WEIGHT_FIELD";
	String EMPTY_PRICE_FIELD = "EMPTY_PRICE_FIELD";
	String EMPTY_PROVIDERR_FIELD = "EMPTY_PROVIDERR_FIELD";
}
