package ua.com.travel.validation;

public interface ValidatorMesseges {

	String EMPTY_USERNAME_FIELD = "EMPTY_USERNAME_FIELD";
	String EMPTY_PASSWORD_FIELD = "EMPTY_PASSWORD_FIELD";
	String EMPTY_EMAIL_FIELD = "EMPTY_EMAIL_FIELD";
	

	
	String NAME_ALREADY_EXIST = "NAME_ALREADY_EXIST";
	String PASSWORD_ALREADY_EXIST = "PASSWORD_ALREADY_EXIST";
	String EMAIL_ALREADY_EXIST = "EMAIL_ALREADY_EXIST";
	
	
	
}
